### ISSUE TITLE
Module (zf-metal\generator) could not be initialized 

### ISSUE THREAD

**Issue by comeUpWithItLater** [zf-metal/generator#12]
Erro when creating module

File:

    /var/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php:54

Message:

    An exception occurred while executing 'INSERT INTO module (name, prefix, path, description, author, license, link, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["PCms", "PCms_", ".\/", "c", "w", "v", "htt", null, null]:

    SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: module.created_at

SQL  in the db Profiler :

INSERT INTO module (name, prefix, path, description, author, license, link, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) Params     1 => string(4) "PCms"
    2 => string(5) "PCms_"
    3 => string(2) "./"
    4 => string(1) "c"
    5 => string(1) "w"
    6 => string(1) "v"
    7 => string(3) "htt"
    8 => NULL
    9 => NULL
Types     1 => string(6) "string"
    2 => string(6) "string"
    3 => string(6) "string"
    4 => string(6) "string"
    5 => string(6) "string"
    6 => string(6) "string"
    7 => string(6) "string"
    8 => string(8) "datetime"
    9 => string(8) "datetime"
Time 0.044059038162231

**Comment by jruvinski** [comment]
Some news about this error? This is happening for me too...

**Comment by cincarnato** [comment]
Sorry. I am late.

module.created_at need dependency  "gedmo/doctrine-extensions"

I will add the dependency on the composer.json in the next version

require: {
 "gedmo/doctrine-extensions": "^2.4",
}

**Comment by cincarnato** [comment]
I add version 1.2.0 with module dependencies verification, and add the list of modules in readme
