### ISSUE TITLE
Problem to initalize module

### ISSUE THREAD

**Issue by matheusdelima** [zf-metal/generator#14]
Unable to resolve service "FilterManager" to a factory; are you certain you provided it during configuration?

**Comment by cincarnato** [comment]
Add     'ZfMetal\Commons' and 'ZfMetal\Datagrid', to modules.config.php

I will add this in documentation

**Comment by cincarnato** [comment]
I add version 1.2.0 with module dependencies verification, and add the list of modules in readme
