### ISSUE TITLE
Unable to resolve service "orm_zf_metal_generator" to a factory;

### ISSUE THREAD

**Issue by matheusdelima** [zf-metal/generator#15]
Zend\ServiceManager\Exception\ServiceNotFoundException: Unable to resolve service "orm_zf_metal_generator" to a factory; are you certain you provided it during configuration? in /media/mano/0347EEDD693ABEBB/Websites/residencia-medica/residencia/vendor/zendframework/zend-servicemanager/src/ServiceManager.php on line 687

**Comment by matheusdelima** [comment]
?

**Comment by matheusdelima** [comment]
how to implement this module?  help-me please!

**Comment by cincarnato** [comment]
I know.. I'm late. . Sorry.

The error sounds like the module was not initialized

Add in your modules.config.php  'ZfMetal\Generator'. I recomend add in development mode.

**Comment by cincarnato** [comment]
I add version 1.2.0 with module dependencies verification, and add the list of modules in readme
