### ISSUE TITLE
/generator/main  404

### ISSUE THREAD

**Issue by merabchik** [zf-metal/generator#16]
router not found, how can I resolve this issue?

**Comment by cincarnato** [comment]
Do you add the module 'ZfMetal\Generator' in modules.config.php ?

**Comment by cincarnato** [comment]
I add version 1.2.0 with module dependencies verification, and add the list of modules in readme

**Comment by merabchik** [comment]
Ok I see it, thanks, there want a shared folder for bootstrap library, I can make a folder and store there bootstrap library but it's will be better if automatically creating that solution

**Comment by merabchik** [comment]
"Unable to resolve service "FilterManager" to a factory; are you certain you provided it during configuration?"
What the configuration must provide?
